- name: install pip
  yum:
    name: python3-pip
    state: present

- name: pip install docker-py
  pip:
    name: docker
    
- name: autre
  pip:
    name: docker-compose

- name: run container
  docker_container:
    name: wartest
    image: "{{ image }}"
    ports: 8081:8080
    state: started
 
